### ISSUE TITLE
Read actual calibration records 

### ISSUE THREAD

**Issue by scottleibrand** [openaps/dexcom_reader#4]
We should add support for retrieval of Dexcom's calibration records (slope, intercept, etc.) so we can properly use the raw filtered and unfiltered records.

**Comment by bewest** [comment]
I looked at android-uploader, but had a tough time grokking the record format.  Can someone explain it?
- https://github.com/nightscout/android-uploader/blob/master/core/src/main/java/com/nightscout/core/dexcom/records/CalRecord.java
- https://github.com/nightscout/android-uploader/blob/master/core/src/main/java/com/nightscout/core/dexcom/records/CalRecord.java
- https://github.com/openaps/dexcom_reader/blob/master/dexcom_reader/database_records.py#L113 This needs a `FORMAT` field defined.

**Comment by bewest** [comment]
Just landed in `dev` https://gist.github.com/bewest/703e54b71c07cc5bcf6a7f6fe9e57a2f#file-calibrations-json, https://github.com/openaps/openaps/pull/90.

**Comment by bewest** [comment]
Just released in dexcom_reader... migrating towards openaps shortly.
