### ISSUE TITLE
support g5 usb better

### ISSUE THREAD

**Issue by bewest** [openaps/dexcom_reader#5]
some support is already here:
- https://github.com/bewest/dexcom_reader/compare/master...loudnate:loudnate/g5-receiver?expand=1

**Comment by bewest** [comment]
Some people have managed to simply install @loudnate's version using `sudo pip install git+git://github.com/loudnate/dexcom_reader.git@loudnate/g5-receiver` to get basic usb reports working with g5 receiver.

**Comment by bewest** [comment]
This is to help track requests from @wgs4 and others who would like better G5 usb support. BLE support for G5 should be handled in a different issue, as well as BLE support for G4+Share.

**Comment by bewest** [comment]
Support for G5 cable just landed in dev.  Many thanks to @loudnate for getting all the new fields.  Testers wanted. https://github.com/openaps/dexcom_reader/pull/3

**Comment by loudnate** [comment]
:+1:!

**Comment by bewest** [comment]
Just released.  Open any bugs/issues. :-)
